// Additive migration: v1 rows and ten-column runs table remain readable.
export function migrateV2(db) {
  db.exec(
    [
      'CREATE TABLE IF NOT EXISTS shift_publications (scenario_id TEXT NOT NULL, content_version TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, content_hash TEXT NOT NULL, rules_hash TEXT NOT NULL, published_at INTEGER NOT NULL, PRIMARY KEY(scenario_id,content_version), FOREIGN KEY(scenario_id,content_version) REFERENCES scenarios(id,version))',
      'CREATE TABLE IF NOT EXISTS shift_meta (run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE, engine_version TEXT NOT NULL, schema_version INTEGER NOT NULL, content_hash TEXT NOT NULL, rules_hash TEXT NOT NULL, initial_state TEXT NOT NULL)',
      'CREATE TABLE IF NOT EXISTS shift_events (run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, seq INTEGER NOT NULL, event_key TEXT NOT NULL, document TEXT NOT NULL, PRIMARY KEY(run_id,seq), UNIQUE(run_id,event_key))',
      'CREATE TABLE IF NOT EXISTS shift_transitions (run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, revision INTEGER NOT NULL, input TEXT NOT NULL, accepted_at INTEGER NOT NULL, request_id TEXT, checkpoint TEXT NOT NULL, PRIMARY KEY(run_id,revision))',
      'CREATE TABLE IF NOT EXISTS motivation_periods (id TEXT PRIMARY KEY, start_at INTEGER NOT NULL, end_at INTEGER NOT NULL, manifest TEXT NOT NULL, state TEXT NOT NULL, archive TEXT)',
      'CREATE TABLE IF NOT EXISTS practice_accounts (profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE, xp INTEGER NOT NULL DEFAULT 0, last_practice_at INTEGER, first_visit_at INTEGER NOT NULL, last_visit_at INTEGER NOT NULL, visit_id INTEGER NOT NULL, return_pending INTEGER NOT NULL DEFAULT 0, return_gap_at INTEGER, consumed_gap_at INTEGER, next_goal INTEGER NOT NULL DEFAULT 2, paused INTEGER NOT NULL DEFAULT 0, automatic_notices INTEGER NOT NULL DEFAULT 1)',
      'CREATE TABLE IF NOT EXISTS motivation_entries (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), band TEXT NOT NULL, organization TEXT NOT NULL, opt_in INTEGER NOT NULL, joined_at INTEGER NOT NULL, score INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(profile_id,period_id))',
      'CREATE TABLE IF NOT EXISTS competition_attempts (run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), slot_id TEXT NOT NULL, ordinal INTEGER NOT NULL CHECK(ordinal IN (1,2)), score INTEGER NOT NULL DEFAULT 0, finished INTEGER NOT NULL DEFAULT 0, technical INTEGER NOT NULL DEFAULT 0, UNIQUE(profile_id,period_id,slot_id,ordinal))',
      'CREATE TABLE IF NOT EXISTS practice_credits (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), family_id TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount IN (10,20)), PRIMARY KEY(profile_id,period_id,family_id))',
      'CREATE TABLE IF NOT EXISTS debrief_acks (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), at INTEGER NOT NULL, receipt TEXT NOT NULL, PRIMARY KEY(profile_id,run_id))',
      'CREATE TABLE IF NOT EXISTS practice_goals (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), target INTEGER NOT NULL CHECK(target IN (1,2,3)), days TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, paused INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(profile_id,period_id))',
      'CREATE TABLE IF NOT EXISTS practice_awards (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, achievement_id TEXT NOT NULL, rule_version TEXT NOT NULL, at INTEGER NOT NULL, evidence TEXT NOT NULL, PRIMARY KEY(profile_id,achievement_id,rule_version))',
      'CREATE TABLE IF NOT EXISTS legacy_awards (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, achievement_id TEXT NOT NULL, at INTEGER NOT NULL, PRIMARY KEY(profile_id,achievement_id))',
      'CREATE TABLE IF NOT EXISTS practice_reviews (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, family_id TEXT NOT NULL, status TEXT NOT NULL, due_date TEXT NOT NULL, criterion_id TEXT, origin_run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE, variant_id TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY(profile_id,family_id))',
      'CREATE TABLE IF NOT EXISTS motivation_notice_views (profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), visit_id INTEGER NOT NULL, notice_id TEXT NOT NULL, at INTEGER NOT NULL, PRIMARY KEY(profile_id,visit_id))',
      'CREATE TABLE IF NOT EXISTS technical_replacements (old_run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, period_id TEXT NOT NULL REFERENCES motivation_periods(id), slot_id TEXT NOT NULL, ordinal INTEGER NOT NULL, at INTEGER NOT NULL, reason TEXT NOT NULL, original_attempt TEXT NOT NULL)',
      'CREATE TABLE IF NOT EXISTS motivation_events (id INTEGER PRIMARY KEY AUTOINCREMENT, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, run_id TEXT REFERENCES runs(id) ON DELETE CASCADE, kind TEXT NOT NULL, at INTEGER NOT NULL, data TEXT NOT NULL)',
      'CREATE TABLE IF NOT EXISTS operator_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, at INTEGER NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, detail TEXT NOT NULL)',
      'CREATE INDEX IF NOT EXISTS competition_period ON competition_attempts(period_id,profile_id)',
      'CREATE INDEX IF NOT EXISTS shift_transitions_owner ON shift_transitions(run_id,revision)',
      'CREATE INDEX IF NOT EXISTS motivation_periods_due ON motivation_periods(state,end_at)',
      'PRAGMA user_version=2',
    ].join(';')
  );
}
